Why not Essential?
blryface/notessential pull request #16
Opened 2024-07-02 00:06 UTC by KTrain5169

branch is also slightly outdated I think

2024-07-02 00:41 UTC, KTrain5169 reviewed
interesting indenting currently

2024-07-02 00:41 UTC, KTrain5169 commented on pages/info.vue
> -                                                                                                            Don't be forced to use Essential. There are countless open-source alternatives to help you.
wtf what happened to the indenting here

2024-07-02 00:41 UTC, KTrain5169 commented on pages/info.vue
> -        <projectContainer class="flex gap-8">
the indenting here is jank

2024-07-02 00:41 UTC, KTrain5169 commented on pages/info.vue
> +            Why are we recommending not to use Essential? This page will list our reasons why you should use alternatives.
might need better wording

2024-07-02 00:41 UTC, KTrain5169 commented on pages/info.vue
> +            But, the very nature of closed-source and obfuscation hinders that in a very big way. If we cannot see the code that is being ran, how can we trust it won't be looking through our files?
and unobfuscated?

2024-07-03 01:34 UTC, Gaming32 commented
I will note that Essential is *not* obfuscated in the slightest.

2024-07-03 02:08 UTC, KTrain5169 commented
I swear it was? If so then I’ll adjust it next time I can get to my computer and start working on this PR. Thanks for letting me know!

Message ID: ***@***.***>

2024-07-04 10:15 UTC, Nitrrine requested changes
I think it will look better if you make buttons on index page to be in row instead of in column.

2024-07-05 04:31 UTC, KTrain5169 commented
![image](https://github.com/blryface/notessential/assets/69028025/7f089513-aafd-40a0-a0b7-37cd96c83418)
lmao

2024-07-05 11:06 UTC, KTrain5169 commented
> ![image](https://private-user-images.githubusercontent.com/43351072/346088125-049849df-9470-4261-a9bb-477885892702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzU0NzEsIm5iZiI6MTcyMDE3NTE3MSwicGF0aCI6Ii80MzM1MTA3Mi8zNDYwODgxMjUtMDQ5ODQ5ZGYtOTQ3MC00MjYxLWE5YmItNDc3ODg1ODkyNzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDEwMjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Mzk0OTczMDBjMDM3YjVmZTM2Zjk2YTZmY2E0MzVmZTA4Y2MyMzFhYWQ4NTMxZjVkMzU5OTBmZTI4OThmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tqy8STAwNvnpYFkqq3Utlt4qln3xVf9SQSTjaF2d9o8)
> 
> It looks good! But make sure so it will transform to column from row on mobile

goddamn it I need to figure out how

2024-07-05 11:25 UTC, KTrain5169 commented
I DID IT YAYY

2024-07-05 13:01 UTC, Nitrrine approved these changes
LGTM!

2024-07-05 13:12 UTC, blryface requested changes
![Screenshot_20240705-101046](https://github.com/blryface/notessential/assets/124838505/944aafed-d758-4b8d-854a-12caa56416db)
Text should be smaller on mobile, and we need to make the info sections shorter so people will actually read it, giving more information in a more general section at the end or something

2024-07-06 01:45 UTC, KTrain5169 commented
> ![Screenshot_20240705-101046](https://private-user-images.githubusercontent.com/124838505/346133405-944aafed-d758-4b8d-854a-12caa56416db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzA1NjksIm5iZiI6MTcyMDIzMDI2OSwicGF0aCI6Ii8xMjQ4Mzg1MDUvMzQ2MTMzNDA1LTk0NGFhZmVkLWQ3NTgtNGI4ZC04NTRhLTEyY2FhNTY0MTZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQwMTQ0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWRjZDhjN2QzMWE2YmU2OTNmZWMzODg3MjI1MTIzODRiOWYxNjU3ODk4ZmFlZGUwNDhiMzY0NTIzOGVlMzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OSiKtulRxDWCw4eluYCY7H223-zzg79D8OTwJYHBEuE) Text should be smaller on mobile, and we need to make the info sections shorter so people will actually read it, giving more information in a more general section at the end or something

I think it would be better to put a short section on index then, after that we can have a learn more button instead of a why not

2024-07-06 02:23 UTC, blryface commented
Sounds good

2024-07-08 12:34 UTC, blryface commented
Will your branch being *very* outdated not cause issues?

2024-07-08 16:18 UTC, blryface approved these changes

2024-07-08 16:53 UTC, blryface commented on pages/index.vue
> +  title: "Home | Not Essential",
With the other changes that happened I have a feeling this PR will cause uh issues

2024-07-08 16:54 UTC, blryface commented on pages/info.vue
This one lgtm

2024-07-08 16:54 UTC, blryface requested changes
Overall looks good, but try updating your branch to prevent issues with new features

2024-07-09 09:22 UTC, KTrain5169 commented
Closing PR, this branch is way too big and messy LMAO

Development will now be moved to the 12-add-the-info branch on blryface/notessential

2024-07-09 09:22 UTC, closed without merging